serviceId: "deployer"
logfile: "dpeloyer.log"
initialiser: "127.0.0.1:5003"
mongo:
  address: "mongodb+srv://mongo2mongo:test123@cluster0.7ik1k.mongodb.net/myFirstDatabase?retryWrites=true&w=majority"
  db:   "node_manager_db"
  collection: "app_deployment_metadata"

kafka: 
  address: "52.140.57.176:9092"