serviceId: "deployer"
logfile: "dpeloyer.log"
initialiser: "127.0.0.1:5003"
mongo:
  address: "20.219.84.37:27017"
  db:   "node_manager_db"
  collection: "app_deployment_metadata"

kafka: 
  address: "20.219.84.36:9092"