kafka:
  group: 'test-consumer-group'
  servers: ['13.71.109.62:9092']
  topic: "deploy_127.0.0.1"
mongo:
  address:    "20.235.9.68:27017"
  db:         "node_manager_db"
  collection: "app_deployment_metadata"