kafka:
  group: 'test-consumer-group'
  servers: ['20.219.84.36:9092']
  topic: "deploy_127.0.0.1"
mongo:
  address:    "20.219.84.37:27017"
  db:         "node_manager_db"
  collection: "app_deployment_metadata"