mongo:
  address:    "mongodb+srv://mongo2mongo:test123@cluster0.7ik1k.mongodb.net/myFirstDatabase?retryWrites=true&w=majority"
  db:         "initialiser_db"
  collection: "running_services"
kafka:
  address: ["52.172.25.250:9092"]



# {"ip": "127.0.0.1", "port": "5005", "service": "deployer", "type": "service"}
# {"ip": "127.0.0.1", "port": "5000", "service": "node-manager", "type": "service"}
# {"ip": "127.0.0.1", "port": "5001", "service": "node-agent1", "type": "node-agent"}
# {"ip": "127.0.0.1", "port": "5004", "service": "scheduler", "type": "service"}