serviceId: "scheduler"
logfile:  "scheduler.log"
initialiser:  "127.0.0.1:5003"
node_manager:
  _id: "624afd50c2a6e828c5ea472e" 
mongo:
  address: "20.235.9.68:27017"
  db:  "scheduler_db"
  collection:  "scheduler_metadata"
kafka:
  group: 'test-consumer-group'
  servers: ['13.71.109.62:9092']
  topic: "scheduler"
cron:
  user: "vishal"