serviceId: "deployer"
initialiser:  "20.204.220.240:5003"
mongo:
  address: "mongodb+srv://mongo2mongo:test123@cluster0.7ik1k.mongodb.net/myFirstDatabase?retryWrites=true&w=majority"
  db:  "node_manager_db"
  collection:  "app_deployment_metadata"
  kafka_db: "vm_details"
  kafka_collection: "kafka"
kafka:
  address: ["52.172.25.250:9092"]

